// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TallerMecanico.Models;

#nullable disable

namespace TallerMecanico.Migrations
{
    [DbContext(typeof(TallerMecanicoDbContext))]
    partial class TallerMecanicoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TallerMecanico.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cliente_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteId"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("apellido");

                    b.Property<string>("Correo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("correo");

                    b.Property<string>("Direccion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("direccion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("telefono");

                    b.HasKey("ClienteId")
                        .HasName("PK__clientes__47E34D64AFF9958A");

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("TallerMecanico.Models.DetalleRepuesto", b =>
                {
                    b.Property<int>("DetalleRepuestoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("detalle_repuesto_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetalleRepuestoId"));

                    b.Property<int>("Cantidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("cantidad");

                    b.Property<int>("OrdenId")
                        .HasColumnType("int")
                        .HasColumnName("orden_id");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("precio_unitario");

                    b.Property<int>("RepuestoId")
                        .HasColumnType("int")
                        .HasColumnName("repuesto_id");

                    b.HasKey("DetalleRepuestoId")
                        .HasName("PK__detalle___4D44998C41409EB4");

                    b.HasIndex("OrdenId");

                    b.HasIndex("RepuestoId");

                    b.ToTable("detalle_repuestos", (string)null);
                });

            modelBuilder.Entity("TallerMecanico.Models.DetalleServicio", b =>
                {
                    b.Property<int>("DetalleServicioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("detalle_servicio_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetalleServicioId"));

                    b.Property<int>("Cantidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("cantidad");

                    b.Property<int>("OrdenId")
                        .HasColumnType("int")
                        .HasColumnName("orden_id");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("precio_unitario");

                    b.Property<int>("ServicioId")
                        .HasColumnType("int")
                        .HasColumnName("servicio_id");

                    b.HasKey("DetalleServicioId")
                        .HasName("PK__detalle___DAEBCE12F53ACC35");

                    b.HasIndex("OrdenId");

                    b.HasIndex("ServicioId");

                    b.ToTable("detalle_servicios", (string)null);
                });

            modelBuilder.Entity("TallerMecanico.Models.Especialidade", b =>
                {
                    b.Property<int>("EspecialidadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("especialidad_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EspecialidadId"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("EspecialidadId")
                        .HasName("PK__especial__A9F2CD7135B200A1");

                    b.HasIndex(new[] { "Nombre" }, "UQ__especial__72AFBCC6CDB9ACDA")
                        .IsUnique();

                    b.ToTable("especialidades", (string)null);
                });

            modelBuilder.Entity("TallerMecanico.Models.Marca", b =>
                {
                    b.Property<int>("MarcaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("marca_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MarcaId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("MarcaId")
                        .HasName("PK__marcas__BBC4319133CBDFBB");

                    b.HasIndex(new[] { "Nombre" }, "UQ__marcas__72AFBCC60CBA77B8")
                        .IsUnique();

                    b.ToTable("marcas", (string)null);
                });

            modelBuilder.Entity("TallerMecanico.Models.Mecanico", b =>
                {
                    b.Property<int>("MecanicoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("mecanico_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MecanicoId"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("apellido");

                    b.Property<int>("EspecialidadId")
                        .HasColumnType("int")
                        .HasColumnName("especialidad_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("telefono");

                    b.HasKey("MecanicoId")
                        .HasName("PK__mecanico__B88634A1AECCA46F");

                    b.HasIndex("EspecialidadId");

                    b.ToTable("mecanicos", (string)null);
                });

            modelBuilder.Entity("TallerMecanico.Models.Modelo", b =>
                {
                    b.Property<int>("ModeloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("modelo_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModeloId"));

                    b.Property<int>("MarcaId")
                        .HasColumnType("int")
                        .HasColumnName("marca_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("ModeloId")
                        .HasName("PK__modelos__DBED97613272D5B1");

                    b.HasIndex("MarcaId");

                    b.ToTable("modelos", (string)null);
                });

            modelBuilder.Entity("TallerMecanico.Models.OrdenesTrabajo", b =>
                {
                    b.Property<int>("OrdenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("orden_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrdenId"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("cliente_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pendiente")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaIngreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_ingreso")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("MecanicoId")
                        .HasColumnType("int")
                        .HasColumnName("mecanico_id");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("observaciones");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("int")
                        .HasColumnName("vehiculo_id");

                    b.HasKey("OrdenId")
                        .HasName("PK__ordenes___F983C4DAC78B094D");

                    b.HasIndex("ClienteId");

                    b.HasIndex("MecanicoId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("ordenes_trabajo", (string)null);
                });

            modelBuilder.Entity("TallerMecanico.Models.Pago", b =>
                {
                    b.Property<int>("PagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pago_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PagoId"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Completado")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_pago")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("metodo_pago");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("monto_total");

                    b.Property<int>("OrdenId")
                        .HasColumnType("int")
                        .HasColumnName("orden_id");

                    b.HasKey("PagoId")
                        .HasName("PK__pagos__FFF0A58EA830DA4B");

                    b.HasIndex(new[] { "OrdenId" }, "UQ__pagos__F983C4DBC00D825F")
                        .IsUnique();

                    b.ToTable("pagos", (string)null);
                });

            modelBuilder.Entity("TallerMecanico.Models.Repuesto", b =>
                {
                    b.Property<int>("RepuestoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("repuesto_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RepuestoId"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("precio");

                    b.Property<int>("Stock")
                        .HasColumnType("int")
                        .HasColumnName("stock");

                    b.HasKey("RepuestoId")
                        .HasName("PK__repuesto__E0EEC4DC105D5C3A");

                    b.ToTable("repuestos", (string)null);
                });

            modelBuilder.Entity("TallerMecanico.Models.Role", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("rol_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolId"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("RolId")
                        .HasName("PK__roles__CF32E443E948AEF1");

                    b.HasIndex(new[] { "Nombre" }, "UQ__roles__72AFBCC6B80A53A5")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("TallerMecanico.Models.Servicio", b =>
                {
                    b.Property<int>("ServicioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("servicio_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServicioId"));

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("costo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("ServicioId")
                        .HasName("PK__servicio__AF3A090C70C3AA04");

                    b.ToTable("servicios", (string)null);
                });

            modelBuilder.Entity("TallerMecanico.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("correo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<int>("RolId")
                        .HasColumnType("int")
                        .HasColumnName("rol_id");

                    b.HasKey("UsuarioId")
                        .HasName("PK__usuarios__2ED7D2AFF8314A19");

                    b.HasIndex("RolId");

                    b.HasIndex(new[] { "Correo" }, "UQ__usuarios__2A586E0B922D9B88")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("TallerMecanico.Models.Vehiculo", b =>
                {
                    b.Property<int>("VehiculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("vehiculo_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehiculoId"));

                    b.Property<int?>("Anio")
                        .HasColumnType("int")
                        .HasColumnName("anio");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("cliente_id");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("color");

                    b.Property<int>("ModeloId")
                        .HasColumnType("int")
                        .HasColumnName("modelo_id");

                    b.Property<string>("Patente")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("patente");

                    b.HasKey("VehiculoId")
                        .HasName("PK__vehiculo__1AD380790EBBF3B2");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ModeloId");

                    b.HasIndex(new[] { "Patente" }, "UQ__vehiculo__40228D081BD1E9D3")
                        .IsUnique();

                    b.ToTable("vehiculos", (string)null);
                });

            modelBuilder.Entity("TallerMecanico.Models.DetalleRepuesto", b =>
                {
                    b.HasOne("TallerMecanico.Models.OrdenesTrabajo", "Orden")
                        .WithMany("DetalleRepuestos")
                        .HasForeignKey("OrdenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__detalle_r__orden__619B8048");

                    b.HasOne("TallerMecanico.Models.Repuesto", "Repuesto")
                        .WithMany("DetalleRepuestos")
                        .HasForeignKey("RepuestoId")
                        .IsRequired()
                        .HasConstraintName("FK__detalle_r__repue__628FA481");

                    b.Navigation("Orden");

                    b.Navigation("Repuesto");
                });

            modelBuilder.Entity("TallerMecanico.Models.DetalleServicio", b =>
                {
                    b.HasOne("TallerMecanico.Models.OrdenesTrabajo", "Orden")
                        .WithMany("DetalleServicios")
                        .HasForeignKey("OrdenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__detalle_s__orden__5CD6CB2B");

                    b.HasOne("TallerMecanico.Models.Servicio", "Servicio")
                        .WithMany("DetalleServicios")
                        .HasForeignKey("ServicioId")
                        .IsRequired()
                        .HasConstraintName("FK__detalle_s__servi__5DCAEF64");

                    b.Navigation("Orden");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("TallerMecanico.Models.Mecanico", b =>
                {
                    b.HasOne("TallerMecanico.Models.Especialidade", "Especialidad")
                        .WithMany("Mecanicos")
                        .HasForeignKey("EspecialidadId")
                        .IsRequired()
                        .HasConstraintName("FK__mecanicos__espec__4D94879B");

                    b.Navigation("Especialidad");
                });

            modelBuilder.Entity("TallerMecanico.Models.Modelo", b =>
                {
                    b.HasOne("TallerMecanico.Models.Marca", "Marca")
                        .WithMany("Modelos")
                        .HasForeignKey("MarcaId")
                        .IsRequired()
                        .HasConstraintName("FK__modelos__marca_i__4316F928");

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("TallerMecanico.Models.OrdenesTrabajo", b =>
                {
                    b.HasOne("TallerMecanico.Models.Cliente", "Cliente")
                        .WithMany("OrdenesTrabajos")
                        .HasForeignKey("ClienteId")
                        .IsRequired()
                        .HasConstraintName("FK__ordenes_t__clien__571DF1D5");

                    b.HasOne("TallerMecanico.Models.Mecanico", "Mecanico")
                        .WithMany("OrdenesTrabajos")
                        .HasForeignKey("MecanicoId")
                        .IsRequired()
                        .HasConstraintName("FK__ordenes_t__mecan__59063A47");

                    b.HasOne("TallerMecanico.Models.Vehiculo", "Vehiculo")
                        .WithMany("OrdenesTrabajos")
                        .HasForeignKey("VehiculoId")
                        .IsRequired()
                        .HasConstraintName("FK__ordenes_t__vehic__5812160E");

                    b.Navigation("Cliente");

                    b.Navigation("Mecanico");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("TallerMecanico.Models.Pago", b =>
                {
                    b.HasOne("TallerMecanico.Models.OrdenesTrabajo", "Orden")
                        .WithOne("Pago")
                        .HasForeignKey("TallerMecanico.Models.Pago", "OrdenId")
                        .IsRequired()
                        .HasConstraintName("FK__pagos__orden_id__68487DD7");

                    b.Navigation("Orden");
                });

            modelBuilder.Entity("TallerMecanico.Models.Usuario", b =>
                {
                    b.HasOne("TallerMecanico.Models.Role", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .IsRequired()
                        .HasConstraintName("FK__usuarios__rol_id__3B75D760");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("TallerMecanico.Models.Vehiculo", b =>
                {
                    b.HasOne("TallerMecanico.Models.Cliente", "Cliente")
                        .WithMany("Vehiculos")
                        .HasForeignKey("ClienteId")
                        .IsRequired()
                        .HasConstraintName("FK__vehiculos__clien__46E78A0C");

                    b.HasOne("TallerMecanico.Models.Modelo", "Modelo")
                        .WithMany("Vehiculos")
                        .HasForeignKey("ModeloId")
                        .IsRequired()
                        .HasConstraintName("FK__vehiculos__model__47DBAE45");

                    b.Navigation("Cliente");

                    b.Navigation("Modelo");
                });

            modelBuilder.Entity("TallerMecanico.Models.Cliente", b =>
                {
                    b.Navigation("OrdenesTrabajos");

                    b.Navigation("Vehiculos");
                });

            modelBuilder.Entity("TallerMecanico.Models.Especialidade", b =>
                {
                    b.Navigation("Mecanicos");
                });

            modelBuilder.Entity("TallerMecanico.Models.Marca", b =>
                {
                    b.Navigation("Modelos");
                });

            modelBuilder.Entity("TallerMecanico.Models.Mecanico", b =>
                {
                    b.Navigation("OrdenesTrabajos");
                });

            modelBuilder.Entity("TallerMecanico.Models.Modelo", b =>
                {
                    b.Navigation("Vehiculos");
                });

            modelBuilder.Entity("TallerMecanico.Models.OrdenesTrabajo", b =>
                {
                    b.Navigation("DetalleRepuestos");

                    b.Navigation("DetalleServicios");

                    b.Navigation("Pago");
                });

            modelBuilder.Entity("TallerMecanico.Models.Repuesto", b =>
                {
                    b.Navigation("DetalleRepuestos");
                });

            modelBuilder.Entity("TallerMecanico.Models.Role", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("TallerMecanico.Models.Servicio", b =>
                {
                    b.Navigation("DetalleServicios");
                });

            modelBuilder.Entity("TallerMecanico.Models.Vehiculo", b =>
                {
                    b.Navigation("OrdenesTrabajos");
                });
#pragma warning restore 612, 618
        }
    }
}
